name: web3_auction_example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.3.2
  # 로컬 DB 위치 주입
  path_provider: ^2.1.3
  # DI
  get_it: ^8.0.0
  # State Management
  hooks_riverpod: ^2.5.4
  flutter_hooks: ^0.20.5
  # Modeling
  riverpod_annotation: ^2.5.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # Http 통신
  dio: ^5.4.3+1
  # 로거
  logger: ^2.3.0
  # Web3
  web3dart: ^2.7.3
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

  isar_generator: ^3.1.0+1

  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.14
  # Modeling
  freezed: ^2.5.7
  json_serializable: ^6.8.0

dependency_overrides:
  analyzer: ^6.7.0 # 두 패키지의 analyzer 버전을 강제 통일

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: fonts/NotoSans-Regular.ttf
  #       - asset: fonts/NotoSans-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
