name: web3_auction_example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

# How TO Run Script
# dart pub global activate derry
# derry ~
scripts:
  build_runner: ./scripts/build_runner.sh

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Local Database
  isar: ^3.1.0
  ## https://github.com/MrLittleWhite/isar_flutter_libs
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  flutter_secure_storage: ^9.2.2
  # 로컬 DB 위치 주입
  path_provider: ^2.1.3
  # DI
  get_it: ^8.0.0
  # State Management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  # Modeling
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  # Http 통신
  dio: ^5.4.3+1
  # 로거
  logger: ^2.3.0
  # Web3
  web3dart: ^2.7.3
  http: ^1.2.2
  flutter_dotenv: ^5.2.1

  # 라우팅
  go_router: ^13.1.0

  # Wallet
  bip39: ^1.0.6
  bip32: ^2.0.0
  uuid: ^4.5.1

  # UI
  # Loading Widget
  shimmer: ^3.0.0
  # Localization
  flutter_localizations: # Add
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4

  build_runner: ^2.4.10
  riverpod_generator: ^2.4.0
  # Modeling
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0
  # Routing
  go_router_builder: ^2.4.1

  analyzer: ^5.0.0
  collection: any

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .env.test
    - assets/abi/NftSaleable.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: fonts/NotoSans-Regular.ttf
  #       - asset: fonts/NotoSans-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
